Modified TS Generator to create one package.json file for all .lf files in the same directory. That way the package.json can describe one shared node_modules for all generated code directories. ALSO I modified run-lf-tests when it has the argument "TS" to automatically delete the package.json in the root of the test directory, Otherwise an out-of-sync package.json could be used for the tests.

diff --git a/bin/run-lf-tests b/bin/run-lf-tests
--- a/bin/run-lf-tests
+++ b/bin/run-lf-tests
@@ -14,65 +14,69 @@ else
 fi
 
 if [ "$1" == '' ]; then
-	echo "Usage: run-lf-tests [target]";
+    echo "Usage: run-lf-tests [target]";
 else
-	ext=$(echo "$1" | awk '{print tolower($0)}')
-	test_dir="$base""org.icyphy.linguafranca/src/test/""$1";
-	manifest="$base""org.icyphy.linguafranca/src/test/test-manifest";
-    	offset="../../../../../";
-	total=0;
-	correct=0;
-	failed="";
+    ext=$(echo "$1" | awk '{print tolower($0)}')
+    test_dir="$base""org.icyphy.linguafranca/src/test/""$1";
+    manifest="$base""org.icyphy.linguafranca/src/test/test-manifest";
+    offset="../../../../../";
+    total=0;
+    correct=0;
+    failed="";
 
-	if [ ! -f "$manifest" ]; then
-		echo "Unable to locate manifest.";
-		echo "File not found: ""$manifest";
-	else
-		pushd $test_dir;
-        	eval $offset"bin/lfc"; # trigger fresh build if necessary
-		while read p; do
-			if [[ "$p" =~ ^[[:space:]]*#.* ]]; then
-    			#echo "Ignoring commented out test: $p";
-				continue;
-			fi
-			if [ ! -f "$p" ]; then
-    				echo "[WARNING] $p does not exist.";
-				continue
-			fi
-			echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++";
-			total=$((total + 1))
-			name=$(echo $p | rev | cut -d. -f2 | rev)
-			echo $p;
-			echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++";
-			echo "================================================================================";
-			eval "$offset""bin/lfc ""$p";
-			echo "================================================================================";
-			if [ $1 == "Cpp" ]; then
-				command="bin/$name --timeout 1"
-			elif [ $1 == "C" ]; then
-				command="bin/$name -timeout 1 sec"
-			elif [ $1 == "TS" ]; then
-				command="node ${name}/dist/${name}"".js"
-			else
-				echo "Unknown target. Valid targets are: \"Cpp\", \"TS\", and \"C\".";
-				exit 1;
-			fi
-			echo "Executing command:"$command;
-			echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>";
-			eval $command;
-			if (($? == 0)); then
-				correct=$((correct + 1))
-			else
-				failed="$name $failed"
-			fi
-			echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>";
-		done <"../test-manifest"
-		echo "--------------------------------------------------------------------------------";		
-		echo "Number of tests passed: ("$correct"/"$total")";
-		echo "--------------------------------------------------------------------------------";
-		if (($correct != $total)); then
-			echo "Failed tests: $failed"
-			exit 1;
-		fi
-	fi
+    if [ ! -f "$manifest" ]; then
+        echo "Unable to locate manifest.";
+        echo "File not found: ""$manifest";
+    else
+        pushd $test_dir;
+        eval $offset"bin/lfc"; # trigger fresh build if necessary
+        if [ $1 == "TS" ]; then
+            echo "Executing command: rm package.json"
+            rm package.json
+        fi
+        while read p; do
+            if [[ "$p" =~ ^[[:space:]]*#.* ]]; then
+                #echo "Ignoring commented out test: $p";
+                continue;
+            fi
+            if [ ! -f "$p" ]; then
+                    echo "[WARNING] $p does not exist.";
+                continue
+            fi
+            echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++";
+            total=$((total + 1))
+            name=$(echo $p | rev | cut -d. -f2 | rev)
+            echo $p;
+            echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++";
+            echo "================================================================================";
+            eval "$offset""bin/lfc ""$p";
+            echo "================================================================================";
+            if [ $1 == "Cpp" ]; then
+                command="bin/$name --timeout 1"
+            elif [ $1 == "C" ]; then
+                command="bin/$name -timeout 1 sec"
+            elif [ $1 == "TS" ]; then
+                command="node ${name}/dist/${name}"".js"
+            else
+                echo "Unknown target. Valid targets are: \"Cpp\", \"TS\", and \"C\".";
+                exit 1;
+            fi
+            echo "Executing command:"$command;
+            echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>";
+            eval $command;
+            if (($? == 0)); then
+                correct=$((correct + 1))
+            else
+                failed="$name $failed"
+            fi
+            echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>";
+        done <"../test-manifest"
+        echo "--------------------------------------------------------------------------------";        
+        echo "Number of tests passed: ("$correct"/"$total")";
+        echo "--------------------------------------------------------------------------------";
+        if (($correct != $total)); then
+            echo "Failed tests: $failed"
+            exit 1;
+        fi
+    fi
 fi
