Fixed a bug in run-lf-tests in which build-lfc was not running because it was looking in the wrong directory. Also added a test on the build-lfc exit code to cause run-lf-tests to exit testing as a failure if building failed. Now run-lf-tests successfully builds before testing I removed the extraneous build-lfc command from .travis.yml.

diff --git a/bin/run-lf-tests b/bin/run-lf-tests
--- a/bin/run-lf-tests
+++ b/bin/run-lf-tests
@@ -28,55 +28,62 @@ else
         echo "Unable to locate manifest.";
         echo "File not found: ""$manifest";
     else
-	eval "$offset""bin/build-lfc"
-        pushd $test_dir;
-        if [ $1 == "TS" ]; then
-            echo "Executing command: rm package.json"
-            rm package.json
-        fi
-        while read p; do
-            if [[ "$p" =~ ^[[:space:]]*#.* ]]; then
-                #echo "Ignoring commented out test: $p";
-                continue;
+        bin/build-lfc;
+        build_exit_code=$?;
+        if [ $build_exit_code -ne 0 ]; then
+            echo "Build failed. Exiting run-lf-tests.";
+            exit 1;
+        else 
+    	# eval "bin/build-lfc"
+            pushd $test_dir;
+            if [ $1 == "TS" ]; then
+                echo "Executing command: rm package.json";
+                rm package.json;
             fi
-            if [ ! -f "$p" ]; then
-                    echo "[WARNING] $p does not exist.";
-                continue
-            fi
-            echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++";
-            total=$((total + 1))
-            name=$(echo $p | rev | cut -d. -f2 | rev)
-            echo $p;
-            echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++";
-            echo "================================================================================";
-            eval "$offset""bin/lfc ""$p";
-            echo "================================================================================";
-            if [ $1 == "Cpp" ]; then
-                command="bin/$name --timeout 1"
-            elif [ $1 == "C" ]; then
-                command="bin/$name -timeout 1 sec"
-            elif [ $1 == "TS" ]; then
-                command="node ${name}/dist/${name}"".js"
-            else
-                echo "Unknown target. Valid targets are: \"Cpp\", \"TS\", and \"C\".";
+            while read p; do
+                if [[ "$p" =~ ^[[:space:]]*#.* ]]; then
+                    #echo "Ignoring commented out test: $p";
+                    continue;
+                fi
+                if [ ! -f "$p" ]; then
+                        echo "[WARNING] $p does not exist.";
+                    continue
+                fi
+                echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++";
+                total=$((total + 1))
+                name=$(echo $p | rev | cut -d. -f2 | rev)
+                echo $p;
+                echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++";
+                echo "================================================================================";
+                eval "$offset""bin/lfc ""$p";
+                echo "================================================================================";
+                if [ $1 == "Cpp" ]; then
+                    command="bin/$name --timeout 1"
+                elif [ $1 == "C" ]; then
+                    command="bin/$name -timeout 1 sec"
+                elif [ $1 == "TS" ]; then
+                    command="node ${name}/dist/${name}"".js"
+                else
+                    echo "Unknown target. Valid targets are: \"Cpp\", \"TS\", and \"C\".";
+                    exit 1;
+                fi
+                echo "Executing command:"$command;
+                echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>";
+                eval $command;
+                if (($? == 0)); then
+                    correct=$((correct + 1))
+                else
+                    failed="$name $failed"
+                fi
+                echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>";
+            done <"../test-manifest"
+            echo "--------------------------------------------------------------------------------";        
+            echo "Number of tests passed: ("$correct"/"$total")";
+            echo "--------------------------------------------------------------------------------";
+            if (($correct != $total)); then
+                echo "Failed tests: $failed"
                 exit 1;
             fi
-            echo "Executing command:"$command;
-            echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>";
-            eval $command;
-            if (($? == 0)); then
-                correct=$((correct + 1))
-            else
-                failed="$name $failed"
-            fi
-            echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>";
-        done <"../test-manifest"
-        echo "--------------------------------------------------------------------------------";        
-        echo "Number of tests passed: ("$correct"/"$total")";
-        echo "--------------------------------------------------------------------------------";
-        if (($correct != $total)); then
-            echo "Failed tests: $failed"
-            exit 1;
         fi
     fi
 fi
