Path to the bin folder is corrected

diff --git a/.github/workflows/c-patmos-tests.yml b/.github/workflows/c-patmos-tests.yml
--- a/.github/workflows/c-patmos-tests.yml
+++ b/.github/workflows/c-patmos-tests.yml
@@ -51,9 +51,11 @@ jobs:
           rm -rf test/C/src-gen
       - name: Smoke tests
         run: |
-          for file in $(ls $(pwd)/bin | grep Patmos); do
+          for file in $(find test/C/bin -type f -name '*Patmos*'); do
+            echo "Inspecting file: $file"
+            file "$file"
             echo "Running pasim on $file"
-            pasim $(pwd)/bin/$file || echo "Error running pasim on $file"
+            pasim "$file" || echo "Error running pasim on $file"
           done
       - name: Report to CodeCov
         uses: ./.github/actions/report-code-coverage
